"""add place_kind_mappings for kind-based unification (opentripmap)

Revision ID: 014
Revises: 013
Create Date: 2026-09-18
"""

from alembic import op

revision: str = "014"
down_revision: str | None = "013"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE place_kind_mappings (
            id                    SERIAL PRIMARY KEY,
            source                VARCHAR(100) NOT NULL,
            kind                  VARCHAR(200) NOT NULL,
            unified_category_id   INTEGER NOT NULL REFERENCES unified_categories(id),
            priority              SMALLINT NOT NULL DEFAULT 50,
            confidence            SMALLINT NOT NULL DEFAULT 100,
            is_manual             BOOLEAN NOT NULL DEFAULT TRUE,
            notes                 TEXT,
            created_at            TIMESTAMPTZ DEFAULT NOW(),
            updated_at            TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE (source, kind)
        )
    """)
    op.execute("CREATE INDEX idx_place_kind_mappings_lookup ON place_kind_mappings (source, kind)")

    # Seed opentripmap kind -> leaf category mappings.
    # Priority = specificity: 90+ hyper-specific, 70-85 specific, 40-60 mid,
    # 10-35 broad fallback buckets. The resolver picks the highest priority
    # match and breaks ties deterministically by kind name.
    op.execute("""
        INSERT INTO place_kind_mappings (source, kind, unified_category_id, priority)
        SELECT 'opentripmap', v.kind, c.id, v.priority
        FROM (VALUES
            -- museums & galleries
            ('museums', 'museum', 85),
            ('other_museums', 'museum', 75),
            ('history_museums', 'museum', 90),
            ('biographical_museums', 'museum', 90),
            ('museums_of_science_and_technology', 'museum', 90),
            ('science_museums', 'museum', 90),
            ('local_museums', 'museum', 90),
            ('archaeological_museums', 'museum', 90),
            ('national_museums', 'museum', 90),
            ('military_museums', 'museum', 90),
            ('open_air_museums', 'museum', 90),
            ('railway_museums', 'museum', 90),
            ('maritime_museums', 'museum', 90),
            ('children_museums', 'museum', 90),
            ('aviation_museums', 'museum', 90),
            ('automobile_museums', 'museum', 90),
            ('fashion_museums', 'museum', 90),
            ('computer_museums', 'museum', 90),
            ('other_technology_museums', 'museum', 90),
            ('historic_house_museums', 'museum', 90),
            ('planetariums', 'museum', 80),
            ('art_galleries', 'gallery', 85),
            -- theatre, cinema, music
            ('theatres_and_entertainments', 'theater', 75),
            ('other_theatres', 'theater', 80),
            ('cinemas', 'theater', 85),
            ('concert_halls', 'theater', 85),
            ('opera_houses', 'theater', 90),
            ('music_venues', 'theater', 80),
            ('children_theatres', 'theater', 90),
            ('puppetries', 'theater', 90),
            ('sylvan_theatres', 'theater', 90),
            ('circuses', 'theater', 70),
            ('amphitheatres', 'historical_site', 75),
            -- nightlife & food
            ('nightclubs', 'bar', 85),
            ('bars', 'bar', 90),
            ('pubs', 'bar', 90),
            ('biergartens', 'bar', 80),
            ('casino', 'leisure', 60),
            ('restaurants', 'restaurant', 90),
            ('fast_food', 'restaurant', 85),
            ('foods', 'restaurant', 55),
            ('food_courts', 'restaurant', 75),
            ('cafes', 'cafe', 90),
            ('bakeries', 'cafe', 60),
            ('wineries', 'brewery', 65),
            -- shops & markets
            ('supermarkets', 'supermarket', 90),
            ('marketplaces', 'market', 90),
            ('fish_stores', 'market', 65),
            ('malls', 'shop', 85),
            ('shops', 'shop', 85),
            ('conveniences', 'shop', 70),
            -- accommodation
            ('other_hotels', 'hotel', 80),
            ('accomodations', 'hotel', 45),
            ('resorts', 'hotel', 65),
            ('motels', 'hotel', 75),
            ('guest_houses', 'guesthouse', 90),
            ('hostels', 'hostel', 90),
            ('campsites', 'campsite', 90),
            ('apartments', 'apartment', 85),
            ('alpine_hut', 'guesthouse', 70),
            ('villas_and_chalet', 'guesthouse', 60),
            ('roman_villas', 'historical_site', 85),
            -- religious buildings (single religious leaf in taxonomy)
            ('churches', 'church', 85),
            ('other_churches', 'church', 75),
            ('catholic_churches', 'church', 90),
            ('eastern_orthodox_churches', 'church', 90),
            ('cathedrals', 'church', 95),
            ('monasteries', 'church', 85),
            ('mosques', 'church', 90),
            ('synagogues', 'church', 90),
            ('buddhist_temples', 'church', 90),
            ('hindu_temples', 'church', 90),
            ('egyptian_temples', 'church', 90),
            ('other_temples', 'church', 85),
            ('minarets', 'church', 80),
            ('crypts', 'church', 75),
            -- history, archaeology, fortifications
            ('historic', 'historical_site', 35),
            ('historical_places', 'historical_site', 70),
            ('historic_districts', 'historical_site', 75),
            ('historic_settlements', 'historical_site', 80),
            ('settlements', 'region', 55),
            ('archaeology', 'historical_site', 80),
            ('other_archaeological_sites', 'historical_site', 80),
            ('battlefields', 'historical_site', 80),
            ('necropolises', 'historical_site', 75),
            ('burial_places', 'historical_site', 60),
            ('other_burial_places', 'historical_site', 70),
            ('cemeteries', 'historical_site', 55),
            ('war_graves', 'historical_site', 70),
            ('cave_paintings', 'historical_site', 85),
            ('kremlins', 'historical_site', 85),
            ('hillforts', 'historical_site', 80),
            ('bunkers', 'historical_site', 65),
            ('fortifications', 'historical_site', 70),
            ('other_fortifications', 'historical_site', 70),
            ('defensive_walls', 'historical_site', 70),
            ('fortified_towers', 'landmark', 70),
            ('destroyed_objects', 'historical_site', 30),
            ('mills', 'historical_site', 55),
            ('factories', 'historical_site', 55),
            ('industrial_facilities', 'historical_site', 55),
            ('power_stations', 'historical_site', 40),
            ('mineshafts', 'historical_site', 55),
            ('abandoned_mineshafts', 'historical_site', 60),
            ('abandoned_railway_stations', 'historical_site', 60),
            ('aqueducts', 'historical_site', 70),
            ('roman_bridges', 'historical_site', 80),
            ('wrecks', 'historical_site', 60),
            -- buildings, towers, bridges, monuments
            ('castles', 'landmark', 90),
            ('palaces', 'landmark', 85),
            ('manor_houses', 'historical_site', 60),
            ('skyscrapers', 'landmark', 80),
            ('towers', 'landmark', 70),
            ('other_towers', 'landmark', 70),
            ('watchtowers', 'landmark', 70),
            ('clock_towers', 'landmark', 75),
            ('bell_towers', 'landmark', 75),
            ('water_towers', 'landmark', 55),
            ('transmitter_towers', 'landmark', 40),
            ('observation_towers', 'viewpoint', 80),
            ('view_points', 'viewpoint', 90),
            ('bridges', 'landmark', 75),
            ('other_bridges', 'landmark', 75),
            ('stone_bridges', 'landmark', 75),
            ('suspension_bridges', 'landmark', 80),
            ('moveable_bridges', 'landmark', 75),
            ('footbridges', 'landmark', 65),
            ('viaducts', 'landmark', 70),
            ('lighthouses', 'landmark', 85),
            ('dams', 'landmark', 50),
            ('squares', 'attraction_leaf', 55),
            ('architecture', 'landmark', 30),
            ('historic_architecture', 'historical_site', 35),
            ('other_buildings_and_structures', 'historical_site', 35),
            ('other_buildings', 'historical_site', 35),
            ('fountains', 'monument', 60),
            ('triumphal_archs', 'monument', 85),
            ('pyramids', 'monument', 85),
            ('monuments', 'monument', 80),
            ('monuments_and_memorials', 'monument', 80),
            ('war_memorials', 'monument', 85),
            ('mausoleums', 'monument', 75),
            ('tumuluses', 'monument', 75),
            ('megaliths', 'monument', 80),
            ('dolmens', 'monument', 80),
            ('menhirs', 'monument', 80),
            ('rune_stones', 'monument', 80),
            ('milestones', 'monument', 55),
            ('sundials', 'monument', 60),
            ('sculptures', 'monument', 70),
            ('installation', 'attraction_leaf', 35),
            ('wall_painting', 'attraction_leaf', 45),
            -- nature
            ('mountain_peaks', 'mountain', 90),
            ('volcanoes', 'mountain', 85),
            ('glaciers', 'mountain', 75),
            ('geological_formations', 'nature_park', 40),
            ('rock_formations', 'nature_park', 55),
            ('canyons', 'nature_park', 70),
            ('caves', 'nature_park', 60),
            ('geysers', 'nature_park', 65),
            ('natural_monuments', 'nature_park', 70),
            ('natural', 'nature_park', 30),
            ('natural_springs', 'nature_park', 65),
            ('springs_others', 'nature_park', 60),
            ('nature_reserves', 'nature_park', 85),
            ('nature_reserves_others', 'nature_park', 75),
            ('other_nature_conservation_areas', 'nature_park', 80),
            ('aquatic_protected_areas', 'nature_park', 75),
            ('wildlife_reserves', 'nature_park', 80),
            ('national_parks', 'nature_park', 95),
            ('rivers', 'nature_park', 55),
            ('canals', 'nature_park', 50),
            ('water', 'nature_park', 30),
            ('reservoirs', 'nature_park', 40),
            ('islands', 'nature_park', 45),
            ('other_islands', 'nature_park', 45),
            ('inland_islands', 'nature_park', 45),
            ('desert_islands', 'nature_park', 45),
            ('tidal_islands', 'nature_park', 45),
            ('high_islands', 'nature_park', 45),
            ('gardens_and_parks', 'park', 80),
            ('beaches', 'beach', 85),
            ('other_beaches', 'beach', 80),
            ('shingle_beaches', 'beach', 85),
            ('golden_sand_beaches', 'beach', 85),
            ('white_sand_beaches', 'beach', 85),
            ('rocks_beaches', 'beach', 85),
            ('black_sand_beaches', 'beach', 85),
            ('nude_beaches', 'beach', 80),
            ('urbans_beaches', 'beach', 80),
            ('lakes', 'lake', 85),
            ('other_lakes', 'lake', 80),
            ('crater_lakes', 'lake', 85),
            ('salt_lakes', 'lake', 80),
            ('dry_lakes', 'lake', 70),
            ('rift_lakes', 'lake', 85),
            ('lagoons', 'lake', 80),
            ('waterfalls', 'waterfall', 90),
            ('farms', 'attraction_leaf', 45),
            -- wellness & sport
            ('baths_and_saunas', 'spa', 85),
            ('saunas', 'spa', 85),
            ('thermal_baths', 'spa', 90),
            ('other_bathhouses', 'spa', 80),
            ('open_air_baths', 'spa', 85),
            ('hot_springs', 'spa', 65),
            ('sport', 'sports', 60),
            ('stadiums', 'sports', 80),
            ('climbing', 'climbing', 90),
            ('diving', 'swimming', 70),
            ('dive_spots', 'swimming', 70),
            ('surfing', 'swimming', 70),
            ('kitesurfing', 'swimming', 70),
            ('skiing', 'skiing', 90),
            ('winter_sports', 'skiing', 80),
            ('other_winter_sports', 'skiing', 80),
            ('cross_country_skiing', 'skiing', 85),
            ('pools', 'swimming', 80),
            ('water_parks', 'swimming', 80),
            ('picnic_site', 'leisure', 55),
            ('outdoor', 'leisure', 40),
            -- family attractions
            ('zoos', 'zoo', 95),
            ('aquariums', 'zoo', 90),
            ('amusement_parks', 'attraction_leaf', 90),
            ('amusements', 'attraction_leaf', 60),
            ('other_amusement_rides', 'attraction_leaf', 80),
            ('ferris_wheels', 'attraction_leaf', 85),
            ('roller_coasters', 'attraction_leaf', 85),
            ('miniature_parks', 'attraction_leaf', 85),
            ('tourist_facilities', 'attraction_leaf', 45),
            -- transport
            ('railway_stations', 'station', 95),
            ('heritage_railways', 'tour', 70),
            ('transport', 'station', 30),
            -- broad fallback buckets
            ('urban_environment', 'attraction_leaf', 25),
            ('cultural', 'attraction_leaf', 25),
            ('religion', 'church', 40),
            ('other', 'attraction_leaf', 10)
        ) AS v(kind, leaf_slug, priority)
        JOIN unified_categories c ON c.slug = v.leaf_slug
    """)


def downgrade() -> None:
    op.drop_table("place_kind_mappings")
