"""Country name variants -> ISO 3166-1 alpha-2, used by data-quality scripts."""

from __future__ import annotations

import re
import unicodedata

# English + common native/alternate country names observed in the store.
COUNTRY_VARIANTS: dict[str, str] = {
    # Europe
    "albania": "AL",
    "shqiperia": "AL",
    "andorra": "AD",
    "austria": "AT",
    "osterreich": "AT",
    "belarus": "BY",
    "belgium": "BE",
    "belgie - belgique - belgien": "BE",
    "bosnia and herzegovina": "BA",
    "bosna i hercegovina": "BA",
    "bulgaria": "BG",
    "croatia": "HR",
    "hrvatska": "HR",
    "cyprus": "CY",
    "czechia": "CZ",
    "czech republic": "CZ",
    "ceska republika": "CZ",
    "denmark": "DK",
    "danmark": "DK",
    "estonia": "EE",
    "eesti": "EE",
    "faroe islands": "FO",
    "finland": "FI",
    "suomi": "FI",
    "france": "FR",
    "germany": "DE",
    "deutschland": "DE",
    "gibraltar": "GI",
    "greece": "GR",
    "hellas": "GR",
    "hungary": "HU",
    "magyarorszag": "HU",
    "iceland": "IS",
    "island": "IS",
    "ireland": "IE",
    "italy": "IT",
    "italia": "IT",
    "kosovo": "XK",
    "kosova": "XK",
    "latvia": "LV",
    "latvija": "LV",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "lietuva": "LT",
    "luxembourg": "LU",
    "malta": "MT",
    "moldova": "MD",
    "monaco": "MC",
    "montenegro": "ME",
    "crna gora": "ME",
    "netherlands": "NL",
    "nederland": "NL",
    "holland": "NL",
    "north macedonia": "MK",
    "macedonia": "MK",
    "norway": "NO",
    "norge": "NO",
    "poland": "PL",
    "polska": "PL",
    "portugal": "PT",
    "romania": "RO",
    "russia": "RU",
    "russian federation": "RU",
    "san marino": "SM",
    "serbia": "RS",
    "slovakia": "SK",
    "slovensko": "SK",
    "slovenia": "SI",
    "slovenija": "SI",
    "spain": "ES",
    "espana": "ES",
    "sweden": "SE",
    "sverige": "SE",
    "switzerland": "CH",
    "schweiz": "CH",
    "suisse": "CH",
    "svizzera": "CH",
    "ukraine": "UA",
    "united kingdom": "GB",
    "great britain": "GB",
    "uk": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "northern ireland": "GB",
    "vatican": "VA",
    "citta del vaticano": "VA",
    "vatican city": "VA",
    # Americas
    "argentina": "AR",
    "aruba": "AW",
    "bahamas": "BS",
    "the bahamas": "BS",
    "barbados": "BB",
    "belize": "BZ",
    "bermuda": "BM",
    "bolivia": "BO",
    "brazil": "BR",
    "brasil": "BR",
    "canada": "CA",
    "chile": "CL",
    "colombia": "CO",
    "costa rica": "CR",
    "cuba": "CU",
    "curacao": "CW",
    "dominica": "DM",
    "dominican republic": "DO",
    "republica dominicana": "DO",
    "ecuador": "EC",
    "el salvador": "SV",
    "republica de el salvador": "SV",
    "greenland": "GL",
    "grenada": "GD",
    "guatemala": "GT",
    "guyana": "GY",
    "haiti": "HT",
    "honduras": "HN",
    "jamaica": "JM",
    "mexico": "MX",
    "nicaragua": "NI",
    "panama": "PA",
    "paraguay": "PY",
    "peru": "PE",
    "puerto rico": "PR",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "st lucia": "LC",
    "saint vincent and the grenadines": "VC",
    "suriname": "SR",
    "trinidad and tobago": "TT",
    "united states of america": "US",
    "united states": "US",
    "usa": "US",
    "uruguay": "UY",
    "venezuela": "VE",
    # Asia / Middle East
    "afghanistan": "AF",
    "armenia": "AM",
    "azerbaijan": "AZ",
    "bahrain": "BH",
    "bangladesh": "BD",
    "bhutan": "BT",
    "brunei": "BN",
    "cambodia": "KH",
    "china": "CN",
    "georgia": "GE",
    "hong kong": "HK",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "israel": "IL",
    "japan": "JP",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "laos": "LA",
    "lebanon": "LB",
    "macau": "MO",
    "malaysia": "MY",
    "maldives": "MV",
    "mongolia": "MN",
    "myanmar": "MM",
    "burma": "MM",
    "nepal": "NP",
    "north korea": "KP",
    "korea, north": "KP",
    "oman": "OM",
    "pakistan": "PK",
    "palestine": "PS",
    "philippines": "PH",
    "qatar": "QA",
    "saudi arabia": "SA",
    "singapore": "SG",
    "south korea": "KR",
    "korea, south": "KR",
    "korea": "KR",
    "sri lanka": "LK",
    "syria": "SY",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "thailand": "TH",
    "timor-leste": "TL",
    "turkey": "TR",
    "turkiye": "TR",
    "suriya": "SY",
    "suriyya": "SY",
    "turkmenistan": "TM",
    "united arab emirates": "AE",
    "uzbekistan": "UZ",
    "vietnam": "VN",
    "viet nam": "VN",
    "yemen": "YE",
    # Africa
    "algeria": "DZ",
    "angola": "AO",
    "benin": "BJ",
    "botswana": "BW",
    "burkina faso": "BF",
    "burundi": "BI",
    "cameroon": "CM",
    "cape verde": "CV",
    "central african republic": "CF",
    "chad": "TD",
    "congo": "CG",
    "democratic republic of the congo": "CD",
    "dr congo": "CD",
    "djibouti": "DJ",
    "egypt": "EG",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "ethiopia": "ET",
    "gabon": "GA",
    "gambia": "GM",
    "ghana": "GH",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "ivory coast": "CI",
    "cote d'ivoire": "CI",
    "kenya": "KE",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "madagascar": "MG",
    "malawi": "MW",
    "mali": "ML",
    "mauritania": "MR",
    "mauritius": "MU",
    "morocco": "MA",
    "maroc": "MA",
    "mozambique": "MZ",
    "namibia": "NA",
    "niger": "NE",
    "nigeria": "NG",
    "rwanda": "RW",
    "senegal": "SN",
    "seychelles": "SC",
    "sierra leone": "SL",
    "somalia": "SO",
    "south africa": "ZA",
    "south sudan": "SS",
    "sudan": "SD",
    "tanzania": "TZ",
    "togo": "TG",
    "tunisia": "TN",
    "uganda": "UG",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    # Oceania
    "australia": "AU",
    "fiji": "FJ",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "papua new guinea": "PG",
    "samoa": "WS",
    "solomon islands": "SB",
    "tonga": "TO",
    "vanuatu": "VU",
}

# Non-Latin / native-script names observed in the store (exact, case-insensitive).
NATIVE_VARIANTS: dict[str, str] = {
    "日本": "JP",
    "日本 (japan)": "JP",
    "中国": "CN",
    "中国 (china)": "CN",
    "대한민국": "KR",
    "ประเทศไทย": "TH",
    "ελλάδα": "GR",
    "κύπρος": "CY",
    "россия": "RU",
    "україна": "UA",
    "беларусь": "BY",
    "србија": "RS",
    "македонија": "MK",
    "българия": "BG",
    "монгол улс": "MN",
    "ישראל": "IL",
    "ایران": "IR",
    "پاکستان": "PK",
    "الجزائر": "DZ",
    "مصر": "EG",
    "تونس": "TN",
    "السعودية": "SA",
    "الكويت": "KW",
    "قطر": "QA",
    "البحرين": "BH",
    "عمان": "OM",
    "ليبيا": "LY",
    "سوريا": "SY",
    "الأردن": "JO",
    "македонија (north macedonia)": "MK",
}

# Common ISO3 codes -> ISO2.
ISO3_TO_ISO2: dict[str, str] = {
    "ARE": "AE",
    "ARG": "AR",
    "AUS": "AU",
    "AUT": "AT",
    "BEL": "BE",
    "BGD": "BD",
    "BGR": "BG",
    "BIH": "BA",
    "BRA": "BR",
    "CAN": "CA",
    "CHE": "CH",
    "CHL": "CL",
    "CHN": "CN",
    "COL": "CO",
    "CZE": "CZ",
    "DEU": "DE",
    "DNK": "DK",
    "DZA": "DZ",
    "EGY": "EG",
    "ESP": "ES",
    "EST": "EE",
    "FIN": "FI",
    "FRA": "FR",
    "GBR": "GB",
    "GRC": "GR",
    "HRV": "HR",
    "HUN": "HU",
    "IDN": "ID",
    "IND": "IN",
    "IRL": "IE",
    "IRN": "IR",
    "IRQ": "IQ",
    "ISL": "IS",
    "ISR": "IL",
    "ITA": "IT",
    "JOR": "JO",
    "JPN": "JP",
    "KAZ": "KZ",
    "KOR": "KR",
    "LBN": "LB",
    "LKA": "LK",
    "LTU": "LT",
    "LUX": "LU",
    "LVA": "LV",
    "MAR": "MA",
    "MEX": "MX",
    "MKD": "MK",
    "MLT": "MT",
    "MYS": "MY",
    "NLD": "NL",
    "NOR": "NO",
    "NZL": "NZ",
    "PAK": "PK",
    "PHL": "PH",
    "POL": "PL",
    "PRT": "PT",
    "QAT": "QA",
    "ROU": "RO",
    "RUS": "RU",
    "SAU": "SA",
    "SGP": "SG",
    "SRB": "RS",
    "SVK": "SK",
    "SVN": "SI",
    "SWE": "SE",
    "THA": "TH",
    "TUN": "TN",
    "TUR": "TR",
    "TWN": "TW",
    "UKR": "UA",
    "USA": "US",
    "VNM": "VN",
    "ZAF": "ZA",
}

# ISO2 -> English display name (for address synthesis).
ISO2_NAMES: dict[str, str] = {
    "AE": "United Arab Emirates",
    "AL": "Albania",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BA": "Bosnia and Herzegovina",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "BR": "Brazil",
    "CA": "Canada",
    "CH": "Switzerland",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DK": "Denmark",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "GE": "Georgia",
    "GR": "Greece",
    "HR": "Croatia",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KR": "South Korea",
    "KZ": "Kazakhstan",
    "LK": "Sri Lanka",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "MA": "Morocco",
    "MC": "Monaco",
    "ME": "Montenegro",
    "MK": "North Macedonia",
    "MT": "Malta",
    "MX": "Mexico",
    "MY": "Malaysia",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PT": "Portugal",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "SA": "Saudi Arabia",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TW": "Taiwan",
    "UA": "Ukraine",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Vatican City",
    "VN": "Vietnam",
    "XK": "Kosovo",
    "ZA": "South Africa",
}


def fold(value: str) -> str:
    """Lowercase, strip diacritics, collapse whitespace and ampersands."""
    decomposed = unicodedata.normalize("NFKD", value)
    ascii_only = "".join(c for c in decomposed if not unicodedata.combining(c))
    folded = ascii_only.lower().replace("&", "and")
    return re.sub(r"\s+", " ", folded).strip()


def _candidates(raw: str):
    yield raw
    if raw.endswith(")") and "(" in raw:
        outer, inner = raw.rsplit("(", 1)
        yield inner[:-1]
        yield outer
    if raw.lower().endswith(", the"):
        yield raw[: -len(", the")]
    for sep in (" / ", " - ", "/"):
        if sep in raw:
            yield from raw.split(sep)
    if " " in raw:
        tokens = [token for token in raw.split() if len(token) > 1]
        yield from sorted(tokens, key=len, reverse=True)


def resolve_country(raw: str | None) -> str | None:
    """Resolve a raw country string to ISO2, or None when unrecognized."""
    if not raw:
        return None
    value = raw.strip()
    if not value:
        return None
    if re.fullmatch(r"[A-Za-z]{2}", value):
        return value.upper()
    if re.fullmatch(r"[A-Za-z]{3}", value):
        return ISO3_TO_ISO2.get(value.upper())

    for candidate in _candidates(value):
        candidate = candidate.strip()
        if not candidate:
            continue
        direct = candidate.lower()
        if direct in NATIVE_VARIANTS:
            return NATIVE_VARIANTS[direct]
        folded = fold(candidate)
        if folded in COUNTRY_VARIANTS:
            return COUNTRY_VARIANTS[folded]
    return None
